не могу понять почему вылазит ошибка EError:(13, 40) java: incompatible types: java.lang.String cannot be converted to int Reader